#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



total = 0
x_1 = 0
x_2 = 1

while x_2 < 4000000:
    y = x_1
    x_1 = x_2
    x_2 = x_1 + y
    if (x_1%2 == 0):
        total += x_1

print('Sum of even fibonacci terms: ' + str(total))

